services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "parcelpost"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./data-mysql:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - sales_agent_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sales_agent_network

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    networks:
      - sales_agent_network

networks:
  sales_agent_network:

volumes:
  data-mysql:
  cache:
